<?php
/**
 * MicroHub Excel Import v3.0
 * Import papers from Excel files generated by the v3 scraper
 * Supports all new fields: figures, methods, full text, sample prep, fluorophores, etc.
 */

// Add import submenu
add_action('admin_menu', 'microhub_add_import_menu');

function microhub_add_import_menu() {
    add_submenu_page(
        'microhub-settings',
        __('Import Papers', 'microhub'),
        __('Import Papers', 'microhub'),
        'manage_options',
        'microhub-import',
        'microhub_import_page'
    );
}

/**
 * Import page content
 */
function microhub_import_page() {
    // Handle import
    if (isset($_POST['microhub_import']) && check_admin_referer('microhub_import_nonce')) {
        microhub_process_import();
    }
    ?>

    <div class="wrap">
        <h1><?php _e('Import Papers - v3.0', 'microhub'); ?></h1>

        <div class="notice notice-info">
            <p><strong>Supported formats:</strong> Excel (.xlsx), JSON (.json)</p>
            <p>Use the v3 scraper export files for best results with all enrichment data.</p>
        </div>

        <form method="post" action="" enctype="multipart/form-data">
            <?php wp_nonce_field('microhub_import_nonce'); ?>

            <table class="form-table">
                <tr>
                    <th scope="row"><label for="import_file"><?php _e('Import File', 'microhub'); ?></label></th>
                    <td>
                        <input type="file" name="import_file" id="import_file" accept=".xlsx,.json" required />
                        <p class="description"><?php _e('Upload Excel (.xlsx) or JSON (.json) file from the scraper', 'microhub'); ?></p>
                    </td>
                </tr>

                <tr>
                    <th scope="row"><?php _e('Import Options', 'microhub'); ?></th>
                    <td>
                        <label>
                            <input type="checkbox" name="skip_existing" value="1" checked />
                            <?php _e('Skip papers that already exist (based on DOI/PMID)', 'microhub'); ?>
                        </label>
                        <br />
                        <label>
                            <input type="checkbox" name="update_existing" value="1" />
                            <?php _e('Update existing papers with new data', 'microhub'); ?>
                        </label>
                        <br /><br />
                        <label>
                            <input type="checkbox" name="full_text_only" value="1" />
                            <?php _e('Only import papers with full text', 'microhub'); ?>
                        </label>
                        <br />
                        <label>
                            <input type="checkbox" name="with_figures_only" value="1" />
                            <?php _e('Only import papers with figures', 'microhub'); ?>
                        </label>
                    </td>
                </tr>

                <tr>
                    <th scope="row"><label for="batch_size"><?php _e('Batch Size', 'microhub'); ?></label></th>
                    <td>
                        <input type="number" name="batch_size" id="batch_size" value="100" min="10" max="500" />
                        <p class="description"><?php _e('Papers to process per batch (lower = more stable, higher = faster)', 'microhub'); ?></p>
                    </td>
                </tr>
            </table>

            <p class="submit">
                <input type="submit" name="microhub_import" class="button button-primary" value="<?php _e('Import Papers', 'microhub'); ?>" />
            </p>
        </form>

        <hr />

        <h2><?php _e('Supported Fields (v3 Scraper)', 'microhub'); ?></h2>
        
        <div style="display: grid; grid-template-columns: repeat(3, 1fr); gap: 20px;">
            <div>
                <h4>📄 Paper Info</h4>
                <ul>
                    <li>Title, Abstract, Methods</li>
                    <li>DOI, PMID, PMC ID</li>
                    <li>Authors, Journal, Year</li>
                    <li>Citations, Priority Score</li>
                </ul>
            </div>
            
            <div>
                <h4>🔬 Microscopy Tags</h4>
                <ul>
                    <li>Microscopy Techniques</li>
                    <li>Microscope Brands & Models</li>
                    <li>Analysis Software</li>
                    <li>Acquisition Software</li>
                </ul>
            </div>
            
            <div>
                <h4>🧪 Sample & Labels</h4>
                <ul>
                    <li>Sample Preparation</li>
                    <li>Fluorophores & Dyes</li>
                    <li>Organisms</li>
                    <li>Antibodies (RRIDs)</li>
                </ul>
            </div>
            
            <div>
                <h4>📋 Protocols</h4>
                <ul>
                    <li>protocols.io</li>
                    <li>Bio-protocol</li>
                    <li>JoVE</li>
                    <li>Nature/STAR Protocols</li>
                </ul>
            </div>
            
            <div>
                <h4>💾 Data & Code</h4>
                <ul>
                    <li>GitHub/GitLab URLs</li>
                    <li>Zenodo, Figshare, Dryad</li>
                    <li>IDR, BioImage Archive</li>
                    <li>EMPIAR, EMDB</li>
                </ul>
            </div>
            
            <div>
                <h4>🖼️ Figures (NEW!)</h4>
                <ul>
                    <li>Figure URLs</li>
                    <li>Figure Captions</li>
                    <li>Figure Count</li>
                    <li>Supplementary Materials</li>
                </ul>
            </div>
        </div>

        <hr />
        
        <h3><?php _e('Excel Column Mapping', 'microhub'); ?></h3>
        <p>The importer automatically maps these Excel columns:</p>
        <pre style="background: #f1f1f1; padding: 15px; overflow-x: auto;">
Title → post_title (required)
Abstract → post_content / _mh_abstract
Methods → _mh_methods
PMID → _mh_pubmed_id
DOI → _mh_doi
PMC ID → _mh_pmc_id
Authors → _mh_authors
Journal → _mh_journal (also sets mh_journal taxonomy)
Year → _mh_publication_year
Citations → _mh_citation_count
Priority → _mh_priority_score

Microscopy Techniques → mh_technique taxonomy (pipe-separated)
Microscope Brands → mh_microscope_brand taxonomy
Microscope Models → mh_microscope_model taxonomy
Image Analysis Software → mh_analysis_software taxonomy
Image Acquisition Software → mh_acquisition_software taxonomy
Sample Preparation → mh_sample_prep taxonomy
Fluorophores → mh_fluorophore taxonomy
Organisms → mh_organism taxonomy

Protocols → _mh_protocols (JSON)
Protocol URLs → used with Protocols
Repositories → _mh_repositories (JSON)
Repository URLs → used with Repositories
RRIDs → _mh_rrids (JSON)
GitHub URL → _mh_github_url

Figure URLs → _mh_figures (JSON)
Figure Count → _mh_figure_count
Figure Info → parsed into _mh_figures

Has Full Text → _mh_has_full_text
Has Figures → _mh_has_figures
Has Protocols → _mh_has_protocols
Has GitHub → _mh_has_github
Has Data → _mh_has_data
        </pre>
    </div>

    <?php
}

/**
 * Process the import
 */
function microhub_process_import() {
    // Check file upload
    if (!isset($_FILES['import_file']) || $_FILES['import_file']['error'] !== UPLOAD_ERR_OK) {
        echo '<div class="notice notice-error"><p>' . __('Error uploading file.', 'microhub') . '</p></div>';
        return;
    }

    // Increase limits
    @ini_set('memory_limit', '1024M');
    set_time_limit(0);

    $file_path = $_FILES['import_file']['tmp_name'];
    $file_name = $_FILES['import_file']['name'];
    $file_ext = strtolower(pathinfo($file_name, PATHINFO_EXTENSION));

    $skip_existing = isset($_POST['skip_existing']);
    $update_existing = isset($_POST['update_existing']);
    $full_text_only = isset($_POST['full_text_only']);
    $with_figures_only = isset($_POST['with_figures_only']);
    $batch_size = intval($_POST['batch_size'] ?? 100);

    $stats = array(
        'imported' => 0,
        'updated' => 0,
        'skipped' => 0,
        'errors' => 0,
        'with_figures' => 0,
        'with_protocols' => 0,
        'with_full_text' => 0,
    );

    // Process based on file type
    if ($file_ext === 'xlsx') {
        $stats = microhub_import_excel($file_path, $skip_existing, $update_existing, $full_text_only, $with_figures_only, $batch_size);
    } elseif ($file_ext === 'json') {
        $stats = microhub_import_json($file_path, $skip_existing, $update_existing, $full_text_only, $with_figures_only, $batch_size);
    } else {
        echo '<div class="notice notice-error"><p>' . __('Unsupported file format. Use .xlsx or .json', 'microhub') . '</p></div>';
        return;
    }

    // Display results
    ?>
    <div class="notice notice-success">
        <h3>✅ Import Complete!</h3>
        <table class="widefat" style="max-width: 400px;">
            <tr><td>Papers Imported:</td><td><strong><?php echo number_format($stats['imported']); ?></strong></td></tr>
            <tr><td>Papers Updated:</td><td><strong><?php echo number_format($stats['updated']); ?></strong></td></tr>
            <tr><td>Papers Skipped:</td><td><?php echo number_format($stats['skipped']); ?></td></tr>
            <tr><td>Errors:</td><td><?php echo number_format($stats['errors']); ?></td></tr>
            <tr><td colspan="2"><hr></td></tr>
            <tr><td>With Full Text:</td><td><?php echo number_format($stats['with_full_text']); ?></td></tr>
            <tr><td>With Figures:</td><td><?php echo number_format($stats['with_figures']); ?></td></tr>
            <tr><td>With Protocols:</td><td><?php echo number_format($stats['with_protocols']); ?></td></tr>
        </table>
    </div>
    <?php
}

/**
 * Import from Excel file
 */
function microhub_import_excel($file_path, $skip_existing, $update_existing, $full_text_only, $with_figures_only, $batch_size) {
    // Check if PhpSpreadsheet is available
    if (!class_exists('PhpOffice\PhpSpreadsheet\IOFactory')) {
        // Try to load via composer autoload
        $autoload_paths = array(
            ABSPATH . 'vendor/autoload.php',
            WP_CONTENT_DIR . '/vendor/autoload.php',
            plugin_dir_path(__FILE__) . '../vendor/autoload.php',
        );
        
        $loaded = false;
        foreach ($autoload_paths as $path) {
            if (file_exists($path)) {
                require_once $path;
                $loaded = true;
                break;
            }
        }
        
        if (!$loaded || !class_exists('PhpOffice\PhpSpreadsheet\IOFactory')) {
            echo '<div class="notice notice-error"><p>';
            echo __('PhpSpreadsheet library not found. Please install it:', 'microhub');
            echo '<br><code>composer require phpoffice/phpspreadsheet</code>';
            echo '<br><br>Or use JSON format instead.</p></div>';
            return array('imported' => 0, 'updated' => 0, 'skipped' => 0, 'errors' => 1, 'with_figures' => 0, 'with_protocols' => 0, 'with_full_text' => 0);
        }
    }

    $stats = array(
        'imported' => 0,
        'updated' => 0,
        'skipped' => 0,
        'errors' => 0,
        'with_figures' => 0,
        'with_protocols' => 0,
        'with_full_text' => 0,
    );

    try {
        $reader = \PhpOffice\PhpSpreadsheet\IOFactory::createReaderForFile($file_path);
        $reader->setReadDataOnly(true);
        $spreadsheet = $reader->load($file_path);
        $worksheet = $spreadsheet->getActiveSheet();
        
        // Get header row
        $headers = array();
        $header_row = $worksheet->getRowIterator(1, 1)->current();
        $cell_iterator = $header_row->getCellIterator();
        $cell_iterator->setIterateOnlyExistingCells(false);
        
        $col = 0;
        foreach ($cell_iterator as $cell) {
            $headers[$col] = strtolower(trim($cell->getValue() ?? ''));
            $col++;
        }
        
        // Create header map
        $header_map = microhub_create_header_map($headers);
        
        echo '<div class="notice notice-info"><p>Processing Excel file with ' . ($worksheet->getHighestRow() - 1) . ' rows...</p></div>';
        flush();
        
        // Process data rows
        $row_num = 0;
        foreach ($worksheet->getRowIterator(2) as $row) {
            $row_num++;
            
            // Get row data
            $row_data = array();
            $cell_iterator = $row->getCellIterator();
            $cell_iterator->setIterateOnlyExistingCells(false);
            
            $col = 0;
            foreach ($cell_iterator as $cell) {
                $row_data[$col] = $cell->getValue();
                $col++;
            }
            
            // Convert to associative array using header map
            $paper = microhub_map_row_to_paper($row_data, $header_map);
            
            // Apply filters
            if ($full_text_only && empty($paper['has_full_text'])) {
                $stats['skipped']++;
                continue;
            }
            
            if ($with_figures_only && empty($paper['has_figures'])) {
                $stats['skipped']++;
                continue;
            }
            
            // Import the paper
            $result = microhub_import_single_paper($paper, $skip_existing, $update_existing, $stats);
            
            if ($result === 'imported') {
                $stats['imported']++;
            } elseif ($result === 'updated') {
                $stats['updated']++;
            } elseif ($result === 'skipped') {
                $stats['skipped']++;
            } else {
                $stats['errors']++;
            }
            
            // Progress update
            if ($row_num % 500 === 0) {
                echo '<p>Processed ' . number_format($row_num) . ' rows...</p>';
                flush();
            }
        }
        
    } catch (Exception $e) {
        echo '<div class="notice notice-error"><p>Excel Error: ' . esc_html($e->getMessage()) . '</p></div>';
        $stats['errors']++;
    }
    
    return $stats;
}

/**
 * Create header mapping from Excel columns to internal fields
 */
function microhub_create_header_map($headers) {
    $map = array();
    
    $column_mappings = array(
        // Basic fields
        'title' => array('title', 'post_title'),
        'abstract' => array('abstract', 'post_content'),
        'methods' => array('methods'),
        'pmid' => array('pmid', 'pubmed_id', 'pubmed'),
        'doi' => array('doi'),
        'pmc_id' => array('pmc_id', 'pmc id', 'pmcid'),
        'authors' => array('authors'),
        'journal' => array('journal'),
        'year' => array('year', 'publication_year'),
        'citations' => array('citations', 'citation_count'),
        'priority' => array('priority', 'priority_score'),
        
        // URLs
        'doi_url' => array('doi_url', 'doi url'),
        'pubmed_url' => array('pubmed_url', 'pubmed url'),
        'pmc_url' => array('pmc_url', 'pmc url'),
        'github_url' => array('github_url', 'github url'),
        
        // Taxonomies (pipe-separated)
        'microscopy_techniques' => array('microscopy_techniques', 'microscopy techniques', 'techniques'),
        'microscope_brands' => array('microscope_brands', 'microscope brands', 'brands'),
        'microscope_models' => array('microscope_models', 'microscope models', 'models'),
        'analysis_software' => array('image_analysis_software', 'image analysis software', 'analysis_software', 'analysis software'),
        'acquisition_software' => array('image_acquisition_software', 'image acquisition software', 'acquisition_software', 'acquisition software'),
        'sample_preparation' => array('sample_preparation', 'sample preparation'),
        'fluorophores' => array('fluorophores'),
        'organisms' => array('organisms'),
        
        // Resources
        'protocols' => array('protocols'),
        'protocols_urls' => array('protocols_urls', 'protocol_urls', 'protocol urls'),
        'repositories' => array('repositories', 'data_repositories', 'data repositories'),
        'repositories_urls' => array('repositories_urls', 'repository_urls', 'repository urls'),
        'rrids' => array('rrids'),
        'rrids_urls' => array('rrids_urls', 'rrid_urls', 'rrid urls'),
        'rors' => array('rors'),
        'supplementary' => array('supplementary', 'supplementary_materials', 'supplementary materials'),
        
        // Figures
        'figure_count' => array('figure_count', 'figure count'),
        'figure_urls' => array('figure_urls', 'figure urls'),
        'figure_captions' => array('figure_captions', 'figure_info', 'figure info'),
        
        // Flags
        'has_full_text' => array('has_full_text', 'has full text'),
        'has_figures' => array('has_figures', 'has figures'),
        'has_protocols' => array('has_protocols', 'has protocols'),
        'has_github' => array('has_github', 'has github'),
        'has_data' => array('has_data', 'has data'),
    );
    
    foreach ($column_mappings as $field => $possible_names) {
        foreach ($possible_names as $name) {
            $col_index = array_search($name, $headers);
            if ($col_index !== false) {
                $map[$field] = $col_index;
                break;
            }
        }
    }
    
    return $map;
}

/**
 * Map a row of data to paper array
 */
function microhub_map_row_to_paper($row_data, $header_map) {
    $paper = array();
    
    foreach ($header_map as $field => $col_index) {
        $paper[$field] = $row_data[$col_index] ?? '';
    }
    
    return $paper;
}

/**
 * Import a single paper
 */
function microhub_import_single_paper($data, $skip_existing, $update_existing, &$stats) {
    global $wpdb;
    
    // Validate required fields
    $title = trim($data['title'] ?? '');
    if (empty($title)) {
        return 'error';
    }
    
    $doi = trim($data['doi'] ?? '');
    $pmid = trim($data['pmid'] ?? '');
    
    // Check for existing paper
    $existing_id = null;
    
    if ($doi) {
        $existing_id = $wpdb->get_var($wpdb->prepare(
            "SELECT post_id FROM {$wpdb->postmeta} WHERE meta_key = '_mh_doi' AND meta_value = %s LIMIT 1",
            $doi
        ));
    }
    
    if (!$existing_id && $pmid) {
        $existing_id = $wpdb->get_var($wpdb->prepare(
            "SELECT post_id FROM {$wpdb->postmeta} WHERE meta_key = '_mh_pubmed_id' AND meta_value = %s LIMIT 1",
            $pmid
        ));
    }
    
    if ($existing_id) {
        if ($skip_existing && !$update_existing) {
            return 'skipped';
        }
        if (!$update_existing) {
            return 'skipped';
        }
    }
    
    // Create or update post
    $post_data = array(
        'post_title' => sanitize_text_field($title),
        'post_content' => wp_kses_post($data['abstract'] ?? ''),
        'post_type' => 'mh_paper',
        'post_status' => 'publish',
    );
    
    if ($existing_id && $update_existing) {
        $post_data['ID'] = $existing_id;
        $post_id = wp_update_post($post_data);
        $is_update = true;
    } else {
        $post_id = wp_insert_post($post_data);
        $is_update = false;
    }
    
    if (!$post_id || is_wp_error($post_id)) {
        return 'error';
    }
    
    // Save meta fields
    $meta_fields = array(
        '_mh_doi' => $doi,
        '_mh_pubmed_id' => $pmid,
        '_mh_pmc_id' => trim($data['pmc_id'] ?? ''),
        '_mh_authors' => sanitize_text_field($data['authors'] ?? ''),
        '_mh_journal' => sanitize_text_field($data['journal'] ?? ''),
        '_mh_publication_year' => intval($data['year'] ?? 0),
        '_mh_citation_count' => intval($data['citations'] ?? 0),
        '_mh_priority_score' => intval($data['priority'] ?? 0),
        '_mh_abstract' => wp_kses_post($data['abstract'] ?? ''),
        '_mh_methods' => wp_kses_post($data['methods'] ?? ''),
        '_mh_doi_url' => esc_url_raw($data['doi_url'] ?? ''),
        '_mh_pubmed_url' => esc_url_raw($data['pubmed_url'] ?? ''),
        '_mh_pmc_url' => esc_url_raw($data['pmc_url'] ?? ''),
        '_mh_github_url' => esc_url_raw($data['github_url'] ?? ''),
        '_mh_figure_count' => intval($data['figure_count'] ?? 0),
        '_mh_has_full_text' => !empty($data['has_full_text']) ? 1 : 0,
        '_mh_has_figures' => !empty($data['has_figures']) ? 1 : 0,
        '_mh_has_protocols' => !empty($data['has_protocols']) ? 1 : 0,
        '_mh_has_github' => !empty($data['has_github']) ? 1 : 0,
        '_mh_has_data' => !empty($data['has_data']) ? 1 : 0,
    );
    
    foreach ($meta_fields as $key => $value) {
        if ($value !== '' && $value !== 0 && $value !== null) {
            update_post_meta($post_id, $key, $value);
        }
    }
    
    // Track enrichment
    if (!empty($data['has_full_text'])) $stats['with_full_text']++;
    if (!empty($data['has_figures'])) $stats['with_figures']++;
    if (!empty($data['has_protocols'])) $stats['with_protocols']++;
    
    // Set taxonomies from pipe-separated values
    $taxonomy_fields = array(
        'microscopy_techniques' => 'mh_technique',
        'microscope_brands' => 'mh_microscope_brand',
        'microscope_models' => 'mh_microscope_model',
        'analysis_software' => 'mh_analysis_software',
        'acquisition_software' => 'mh_acquisition_software',
        'sample_preparation' => 'mh_sample_prep',
        'fluorophores' => 'mh_fluorophore',
        'organisms' => 'mh_organism',
    );
    
    foreach ($taxonomy_fields as $field => $taxonomy) {
        if (!empty($data[$field])) {
            $terms = array_filter(array_map('trim', explode('|', $data[$field])));
            if (!empty($terms)) {
                wp_set_object_terms($post_id, $terms, $taxonomy);
            }
        }
    }
    
    // Set journal taxonomy
    if (!empty($data['journal'])) {
        wp_set_object_terms($post_id, array(trim($data['journal'])), 'mh_journal');
    }
    
    // Process protocols (pipe-separated names with URLs)
    if (!empty($data['protocols'])) {
        $protocol_names = array_filter(array_map('trim', explode('|', $data['protocols'])));
        $protocol_urls = !empty($data['protocols_urls']) ? array_map('trim', explode('|', $data['protocols_urls'])) : array();
        
        $protocols = array();
        foreach ($protocol_names as $i => $name) {
            $protocols[] = array(
                'source' => sanitize_text_field($name),
                'url' => isset($protocol_urls[$i]) ? esc_url_raw($protocol_urls[$i]) : '',
            );
        }
        
        if (!empty($protocols)) {
            update_post_meta($post_id, '_mh_protocols', wp_json_encode($protocols));
            
            // Also set protocol source taxonomy
            wp_set_object_terms($post_id, $protocol_names, 'mh_protocol_source');
        }
    }
    
    // Process repositories
    if (!empty($data['repositories'])) {
        $repo_names = array_filter(array_map('trim', explode('|', $data['repositories'])));
        $repo_urls = !empty($data['repositories_urls']) ? array_map('trim', explode('|', $data['repositories_urls'])) : array();
        
        $repositories = array();
        foreach ($repo_names as $i => $name) {
            $repositories[] = array(
                'name' => sanitize_text_field($name),
                'url' => isset($repo_urls[$i]) ? esc_url_raw($repo_urls[$i]) : '',
            );
        }
        
        if (!empty($repositories)) {
            update_post_meta($post_id, '_mh_repositories', wp_json_encode($repositories));
            
            // Also set repository taxonomy
            wp_set_object_terms($post_id, $repo_names, 'mh_repository');
        }
    }
    
    // Process RRIDs
    if (!empty($data['rrids'])) {
        $rrid_ids = array_filter(array_map('trim', explode('|', $data['rrids'])));
        $rrid_urls = !empty($data['rrids_urls']) ? array_map('trim', explode('|', $data['rrids_urls'])) : array();
        
        $rrids = array();
        foreach ($rrid_ids as $i => $id) {
            // Determine type from RRID prefix
            $type = 'unknown';
            if (strpos($id, 'AB_') !== false) $type = 'antibody';
            elseif (strpos($id, 'SCR_') !== false) $type = 'software';
            elseif (strpos($id, 'CVCL_') !== false) $type = 'cell_line';
            elseif (strpos($id, 'Addgene_') !== false) $type = 'plasmid';
            
            $rrids[] = array(
                'id' => sanitize_text_field($id),
                'type' => $type,
                'url' => isset($rrid_urls[$i]) ? esc_url_raw($rrid_urls[$i]) : 'https://scicrunch.org/resolver/' . $id,
            );
        }
        
        if (!empty($rrids)) {
            update_post_meta($post_id, '_mh_rrids', wp_json_encode($rrids));
        }
    }
    
    // Process figures
    if (!empty($data['figure_urls'])) {
        $fig_urls = array_filter(array_map('trim', explode('|', $data['figure_urls'])));
        $fig_captions = !empty($data['figure_captions']) ? explode("\n", $data['figure_captions']) : array();
        
        $figures = array();
        foreach ($fig_urls as $i => $url) {
            $figures[] = array(
                'image_url' => esc_url_raw($url),
                'label' => 'Figure ' . ($i + 1),
                'caption' => isset($fig_captions[$i]) ? sanitize_text_field($fig_captions[$i]) : '',
            );
        }
        
        if (!empty($figures)) {
            update_post_meta($post_id, '_mh_figures', wp_json_encode($figures));
            update_post_meta($post_id, '_mh_figure_count', count($figures));
            
            // Use first figure as thumbnail
            if (!empty($figures[0]['image_url'])) {
                update_post_meta($post_id, '_mh_thumbnail_url', $figures[0]['image_url']);
            }
        }
    }
    
    // Process supplementary materials
    if (!empty($data['supplementary'])) {
        $supp_items = array_filter(array_map('trim', explode('|', $data['supplementary'])));
        $supplementary = array_map(function($item) {
            return array('label' => sanitize_text_field($item));
        }, $supp_items);
        
        if (!empty($supplementary)) {
            update_post_meta($post_id, '_mh_supplementary_materials', wp_json_encode($supplementary));
        }
    }
    
    return $is_update ? 'updated' : 'imported';
}

/**
 * Import from JSON file (legacy support)
 */
function microhub_import_json($file_path, $skip_existing, $update_existing, $full_text_only, $with_figures_only, $batch_size) {
    $stats = array(
        'imported' => 0,
        'updated' => 0,
        'skipped' => 0,
        'errors' => 0,
        'with_figures' => 0,
        'with_protocols' => 0,
        'with_full_text' => 0,
    );
    
    $json_content = file_get_contents($file_path);
    $papers = json_decode($json_content, true);
    
    if (!$papers || !is_array($papers)) {
        echo '<div class="notice notice-error"><p>' . __('Invalid JSON format.', 'microhub') . '</p></div>';
        return $stats;
    }
    
    unset($json_content);
    
    $total = count($papers);
    echo '<div class="notice notice-info"><p>Processing ' . number_format($total) . ' papers from JSON...</p></div>';
    
    foreach ($papers as $i => $paper) {
        // Convert JSON format to internal format
        $data = array(
            'title' => $paper['title'] ?? '',
            'abstract' => $paper['abstract'] ?? '',
            'methods' => $paper['methods'] ?? '',
            'doi' => $paper['doi'] ?? '',
            'pmid' => $paper['pmid'] ?? '',
            'pmc_id' => $paper['pmc_id'] ?? '',
            'authors' => $paper['authors'] ?? '',
            'journal' => $paper['journal'] ?? '',
            'year' => $paper['year'] ?? 0,
            'citations' => $paper['citation_count'] ?? $paper['citations'] ?? 0,
            'priority' => $paper['priority_score'] ?? 0,
            'github_url' => $paper['github_url'] ?? '',
            'has_full_text' => $paper['has_full_text'] ?? false,
            'has_figures' => !empty($paper['figures']),
            'has_protocols' => !empty($paper['protocols']),
            
            // Convert arrays to pipe-separated
            'microscopy_techniques' => is_array($paper['microscopy_techniques'] ?? null) ? implode('|', $paper['microscopy_techniques']) : '',
            'microscope_brands' => is_array($paper['microscope_brands'] ?? null) ? implode('|', $paper['microscope_brands']) : '',
            'microscope_models' => is_array($paper['microscope_models'] ?? null) ? implode('|', $paper['microscope_models']) : '',
            'analysis_software' => is_array($paper['image_analysis_software'] ?? null) ? implode('|', $paper['image_analysis_software']) : '',
            'acquisition_software' => is_array($paper['image_acquisition_software'] ?? null) ? implode('|', $paper['image_acquisition_software']) : '',
            'sample_preparation' => is_array($paper['sample_preparation'] ?? null) ? implode('|', $paper['sample_preparation']) : '',
            'fluorophores' => is_array($paper['fluorophores'] ?? null) ? implode('|', $paper['fluorophores']) : '',
            'organisms' => is_array($paper['organisms'] ?? null) ? implode('|', $paper['organisms']) : '',
        );
        
        // Apply filters
        if ($full_text_only && empty($data['has_full_text'])) {
            $stats['skipped']++;
            continue;
        }
        
        if ($with_figures_only && empty($data['has_figures'])) {
            $stats['skipped']++;
            continue;
        }
        
        $result = microhub_import_single_paper($data, $skip_existing, $update_existing, $stats);
        
        if ($result === 'imported') {
            $stats['imported']++;
        } elseif ($result === 'updated') {
            $stats['updated']++;
        } elseif ($result === 'skipped') {
            $stats['skipped']++;
        } else {
            $stats['errors']++;
        }
        
        if (($i + 1) % 500 === 0) {
            echo '<p>Processed ' . number_format($i + 1) . ' of ' . number_format($total) . ' papers...</p>';
            flush();
        }
    }
    
    return $stats;
}
